### ISSUE TITLE
Update gettext-parser version

### ISSUE THREAD

**Issue by kevinlul** [ttag-org/ttag-cli#121]
This project (and `babel-plugin-ttag`) have `gettext-parser` pinned at exactly `4.0.0-alpha.0`, released three years ago. This package is now on [version 5.1.2](https://github.com/smhg/gettext-parser/releases) and should be updated.

**Comment by kevinlul** [comment]
I would like to take this up. Is there a good way to get started?

**Comment by AlexMost** [comment]
Hi, tried to update to the new version. Seems like they have some breaking changes, have some failed tests. Actually, we need to update this package in`babel-plugin-ttag` and `ttag-cli` and to make all tests green.

**Comment by AlexMost** [comment]
Seems like that was an easy one fix, new gettext-parser uses upper case headers instead of lowercase) You can try `ttag-cli@1.10.0` and `babel-plugin-ttag@1.8.0` with the new `gettext-parser` package. Let me know of something goes wrong. Thanks for the issue!

**Comment by jorrit** [comment]
I see you're checking for both lower case and upper case headers now. If gettext-parser 5.1.2 and up use upper case, than theoretically checking the lower case headers is not necessary, right?

**Comment by AlexMost** [comment]
@jorrit you are right, just decided to double check if for some reason the older version of gettext will overlap. Maybe it's unnecessary
