### ISSUE TITLE
consider cutting a release to npm

### ISSUE THREAD

**Issue by siebertm** [ttag-org/ttag-cli#37]
Currently, npmjs.org still has the 0.0.1 release. Installing from git doesnt work (it's missing `dist`), so a proper release would be needed (or check in `dist`)

**Comment by AlexMost** [comment]
Nice catch, thanks

**Comment by AlexMost** [comment]
Hi @siebertm, not sure that I have understood the problem. As far as I can see the last published version on npm is `1.3.0-1` - https://www.npmjs.com/package/ttag-cli?activeTab=versions

**Comment by siebertm** [comment]
Hey @AlexMost, Now, it is better, as there was a release done. On June 27th, when I created, my statement was true :-)

Anyways, closing now!

**Comment by AlexMost** [comment]
NP, thanks for the report!
