### ISSUE TITLE
More CLI options

### ISSUE THREAD

**Issue by snowwm** [ttag-org/ttag-cli#39]
Although `babel-plugin-ttag` is [configurable](https://c-3po.js.org/configuration.html), there's no way to achieve this with `ttag-cli` at the moment. #38 will be a big step forward, but is not very convenient for simple use-cases. I propose something like:

    $ ttag extract --no-import-check --numbered-expressions src/**.js

This will also resolve #35 (support for numberedExpressions flag), and you may add options for other config parameters. Those that do not get added will be still configurable by `.babelrc`.

**Comment by AlexMost** [comment]
you can check version `1.3.1` with `numberedExpressions` and `discover` (no import check) options.
