### ISSUE TITLE
Extract translations when ttag is defined globally

### ISSUE THREAD

**Issue by hackedbellini** [ttag-org/ttag-cli#46]
Hi,

I'm trying to change my project from xgettext to ttag. Before I used `jed` and exported a `_` globally (using `window._ = <function>`)

Trying to use `ttag update` it seems to only get strings from the file that I imported ttag. It would take me a lot of time to add an import in every file that has a `_()` in it.

Is there an easier way of doing that? Is that a bug or something?

**Comment by AlexMost** [comment]
Hi @hackedbellini, currently that is the way `babel-plugin-ttag` works. It looks at imports and after that extracts the translation. Since migration from xgettext is a common scenario, I think we can add a special option for that. 

One thing I want to discuss is how it should behave.

My suggestion is that we can add special option -  `--xgettext`

```
ttag update --xgettext ...
```

And as a result `ttag` will extract all global `_`  functions?

**Comment by AlexMost** [comment]
Another one option is to create jscodeshift that will add an appropriate `import` or `require` to each file that uses `_` function:

before:
```js
_('test');
```

after:
```
import { gettext as _ } from 'ttag';
_('test');
```

**Comment by hackedbellini** [comment]
Hey @AlexMost , I just saw https://github.com/ttag-org/babel-plugin-ttag/pull/110 . Looking at the change I couldn't tell if it already solves my issue here. Does it? If so, how can I use it?

**Comment by AlexMost** [comment]
Hey @hackedbellini,  actually, `babe-plugin-ttag` is ready to solve your issue, but there is still some work on `cli`. That part is a little bit tricky, but I am going to implement that today or tomorrow.

But for now, you can already use the new version of `babel-plugin-ttag@1.3.0` to extract translations, and `ttag merge` to merge extracted translations with your existing file.

1. Extract translations with this option - https://ttag.js.org/docs/plugin-api.html#configextractoutput. 
(just put that configuration somewhere in .babelrc and run `babel`). That will extract translations in the `.pot` file. (template file with translations). To discover `_` function you also need to add a discover option https://ttag.js.org/docs/plugin-api.html#configdiscover.
The resulting configuration inside .babelrc should look like:
```
{
   plugins: [['ttag', { extract: { output: "result.pot"}, discover: ['_'] }
}
```
2. And after that run `ttag merge https://github.com/ttag-org/ttag-cli#merge-path

**Comment by hackedbellini** [comment]
@AlexMost nice!

Ok, just so you know, I updated `babel-plugin-ttag` to `1.3.0` but it didn't work. I don't know if I should extract translations another way, but I was using `ttag extract`. It seems to have get 2 strings defined as `_("xxx")` from a single file, but it ignored everything else.

**Comment by AlexMost** [comment]
my idea was not to use `ttag cli` for `extract` but just `babel`. Anyway, going to push something usable by the end of the day, so you will be able just to use `ttag update`

**Comment by hackedbellini** [comment]
@AlexMost oh I see. But ok, I'll wait for the `ttag cli` update. Please ping me when it's ready and I'll test it right away!

**Comment by AlexMost** [comment]
Hi @hackedbellini, `ttag-cli@1.3.0` is released, so now to solve your issue, you can add the `discover` option to `update` command:
```
ttag update --discover=_ <pofile> <src>
```

**Comment by hackedbellini** [comment]
@AlexMost wow, we live very far from each other! hahaha

Well, regarding the issue, I think you nailed it! It's working perfectly for me, thanks!

Just one small issue: I tried defining `t` as a global variable (using `window.t = t`), but that made it not get the translations from the places using template literals. I importer `t` manually in those files, but is there a way to make it also consider those?

**Comment by AlexMost** [comment]
Glad to hear that it works for you) 

As for `t`, have you tried to pass it as a discover option to?

``
ttag update --discover=_ --discover=t <pofile> <srcPath>
```

**Comment by hackedbellini** [comment]
@AlexMost great, it worked too :)

I think it's time to mark this as resolved. Thank you so much for this! I'm sure that it will help other people as well

**Comment by AlexMost** [comment]
@hackedbellini np) That is a really useful feature update, going to write some doc for those who are trying to migrate from `xgettext`.  
Thanks for the feedback, feel free to post any issues and ideas here!
