### ISSUE TITLE
--discover option does not work

### ISSUE THREAD

**Issue by TiagoDanin** [ttag-org/ttag-cli#49]
**Summary**
--discover option does not work.

Example code: 
```javascript
const { ngettext, msgid, t, addLocale, useLocale } = require('ttag')
const i18n = t

addLocale('pt', require('./pt.po.json'))
useLocale('pt')

const w = i18n`world`
const text = i18n`Hello ${w}`
console.log(text)
```

Command used: `$ npx ttag update pt.po test.js --discover=i18n`

**Current Behavior**:
Output pt.po
```
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"Plural-Forms: nplurals = 2; plural = (n !== 1);\n"
"Language: pt\n"
"MIME-Version: 1.0\n"
"Content-Transfer-Encoding: 8bit\n"
```
**Expected behavior**
Output pt.po
```
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"Plural-Forms: nplurals = 2; plural = (n !== 1);\n"
"Language: pt\n"
"MIME-Version: 1.0\n"
"Content-Transfer-Encoding: 8bit\n"

#: test.js:7
msgid "world"
msgstr ""

#: test.js:8
msgid "Hello ${ w }"
msgstr ""
```

**Environment**
- Ttag version: 1.3.3
- Ttag-cli version: 1.3.3
- Babel-plugin-ttag version: 1.3.2
- Node version: 9.4.0
- Npm version: 6.4.1
- OS: Linux (Manjaro - Kernel 4.14.52)

**Comment by AlexMost** [comment]
Hello @TiagoDanin. By now, to solve your issue, you can just use import aliasing and it should work even without 'discover' option:

```js
const { t as i18n } = require('ttag');
```

You can read more about ttag aliasing here - https://ttag.js.org/docs/aliasing.html

Does it solve your issue?

**Comment by AlexMost** [comment]
You can check `ttag-cli@1.3.4` and this syntax to solve your issue:

```js
const { t: i18n } = require('ttag');
```

Hope that works)

Feel free to report any issues!

**Comment by TiagoDanin** [comment]
Solved! :+1:
