### ISSUE TITLE
ttag validate should return non-zero exit code when errors are found

### ISSUE THREAD

**Issue by MrOrz** [ttag-org/ttag-cli#57]
We put `ttag validate` in CI to verify the automatic pull request sent by translation systems.

However we found that `ttag validate` actually return zero exit code even when translation error is found. Therefore, the CI always pass regardless of the mistake in translation files.

I think at least we should return non-zero exit code when:
- `process.env.CI` exists, and
- mismatch are found

**Comment by alxpy** [comment]
Done -- https://github.com/ttag-org/ttag-cli/pull/59
