### ISSUE TITLE
Support locale territory in `ttag init`

### ISSUE THREAD

**Issue by dimaqq** [ttag-org/ttag-cli#60]
I wish `ttag` and `ttag-cli` supported locale territories, that is `sv_FI` as distinct from `sv_SE`; `zh-TW` vs. `zh`.

Currently, territory is not supported:

```
> ttag init zh-TW int/zh.po
✖ Unknown lang code "zh-TW".

> ttag init zh int/zh.po
✔ [ttag] int/zh.po is created
```

The error message links to http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html which is about plural forms, while (I think) the key is rather that words are sometimes different.

**Comment by AlexMost** [comment]
Hi @dimaqq!
Currently `zh` set's the language, but not specific locale. I think we definitely should add another argument that sets locale. Current option is to create 2 separate `.po` files and edit `.po` headers inside the `.po` file to meet your locale requirements. 

```
ttag init zh int/zh-TW.po
ttag init zh int/zh-SE.po
```
Do those locales have different plurals rules?

**Comment by AlexMost** [comment]
@dimaqq you can checkout out the new version of ttag that supports locales `1.7.0`

This one works
```
ttag init zh-TW int/zh-TW.po
```

**Comment by dimaqq** [comment]
Nice!
As far as I know plural rules are the same.
CLDR is canonical source of truth :)
