### ISSUE TITLE
JSON export format

### ISSUE THREAD

**Issue by dhoko** [ttag-org/ttag-cli#70]
👋 

I'm testing the CLI to convert my po to JSON.
Why do you keep so much details inside the JSON ? The output file is huge:

360Ko vs 204Ko for the same file if I convert it to JSON via [angular-gettext-cli](https://github.com/huston007/angular-gettext-cli) (_as it's done today on the app, we don't use ttag yet_). 
[test po](https://github.com/ProtonMail/WebClient/blob/public/po/pt.po)
[our current json export](https://github.com/ProtonMail/WebClient/blob/public/src/i18n/pt_BR.json)

<details>
<summary>Output from ttag-cli</summary>

```json
{
  "charset": "utf-8",
  "headers": {
    "content-type": "text/plain; charset=UTF-8",
    "content-transfer-encoding": "8bit",
    "project-id-version": "protonmail",
    "plural-forms": "nplurals=2; plural=(n != 1);",
    "x-generator": "crowdin.com",
    "x-crowdin-project": "protonmail",
    "x-crowdin-language": "pt-BR",
    "x-crowdin-file": "ProtonMail Web Application.pot",
    "last-translator": "PMtranslator",
    "language-team": "Portuguese, Brazilian",
    "language": "pt_BR",
    "po-revision-date": "2019-04-17 08:44"
  },
  "translations": {
    "": {
      "": {
        "msgid": "",
        "msgstr": [
          "Content-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nProject-Id-Version: protonmail\nPlural-Forms: nplurals=2; plural=(n != 1);\nX-Generator: crowdin.com\nX-Crowdin-Project: protonmail\nX-Crowdin-Language: pt-BR\nX-Crowdin-File: ProtonMail Web Application.pot\nLast-Translator: PMtranslator\nLanguage-Team: Portuguese, Brazilian\nLanguage: pt_BR\nPO-Revision-Date: 2019-04-17 08:44\n"
        ]
      }
    },
    "1 of 2 contacts successfully imported.": {
      "contacts successfully imported.": {
        "msgid": "contacts successfully imported.",
        "msgctxt": "1 of 2 contacts successfully imported.",
        "msgstr": [
          "contatos importados com sucesso."
        ]
      }
    },
    "1 of 2 contacts successfully merged.": {
      "contacts successfully merged.": {
        "msgid": "contacts successfully merged.",
        "msgctxt": "1 of 2 contacts successfully merged.",
        "msgstr": [
          "contatos mesclados com sucesso."
        ]
      }
    }
}
```
</details> 

vs

<details>
<summary>Output from angular-gettext-cli</summary>

```json
{
  "pt_BR": {
    "contacts successfully imported.": {
      "1 of 2 contacts successfully imported.": "contatos importados com sucesso."
    },
    "contacts successfully merged.": {
      "1 of 2 contacts successfully merged.": "contatos mesclados com sucesso."
    },
    "30 seconds": {
      "2FA setup modal": "30 segundos"
    },
    "6 digits": {
      "2FA setup modal": "6 dígitos"
    },
    "Interval": {
      "2FA setup modal": "Intervalo"
    },
    "Key": {
      "2FA setup modal": "Chave"
    },
    "Length": {
      "2FA setup modal": "Tamanho"
    }
}
```
</details> 

As you can see the diff is huge, the output format is way more verbose via ttag, why ? 
_the diff post gzip is not this huge, but still almost 30% bigger (57ko vs 73ko)_

thx

**Comment by AlexMost** [comment]
Hi @dhoko! Thanks for your report!
I think we should optimize it definitely. Currently, we use to precompile our translations right into the build. But seems like a lot of people use to load translations from JSON. Will inform you about the results here.

**Comment by AlexMost** [comment]
Hi @dhoko. Almost done with the new compact format. I have tested on your `.po` file and got `187K` instead of old `360K`. Going to release a new version tomorrow. You can check PR also https://github.com/ttag-org/ttag-cli/pull/73.

**Comment by AlexMost** [comment]
Finally it was merged. You can try `1.7.13` version of `ttag-cli` and `ttag` library.

To product compact output you must provide `--format=compact` to `ttag-cli@1.7.13`. Soon we will make a minor release release - `1.8.x` and this option will be enabled by default.

Please, let me know if that worked for you.

**Comment by dhoko** [comment]
Ho nice :+1: thx for this feature
indeed it's even smaller, GG :tada:
