### ISSUE TITLE
Release 1.7.18?

### ISSUE THREAD

**Issue by alecf** [ttag-org/ttag-cli#80]
this particular package is responsible for many outdated dependencies in my project, which I updated in #77 - any chance of a release so we can benefit from it? Thanks!

**Comment by AlexMost** [comment]
Hi @alecf ! I have investigated in failing tests issue and found that they are not falling on 1.7.17 tag. But start to fail after your PR. Trying to find out how to fix them

**Comment by AlexMost** [comment]
All CI issues are fixed. You can try out the new version `+ ttag-cli@1.7.18` 🎉
