### ISSUE TITLE
can't run ttag update with context

### ISSUE THREAD

**Issue by hitbear518** [ttag-org/ttag-cli#81]
When I run ttag update with c('context').t\`key\` in my source code,
I got ```UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object```

**Comment by AlexMost** [comment]
Hi @hitbear518 ! Thanks for the report, seems like a bug

**Comment by AlexMost** [comment]
Fix is available in `1.7.20`. Please, let me know if this works for you

**Comment by forkerino** [comment]
The error is gone, but I have some weird behavior with context, I'll open a new issue.
