### ISSUE TITLE
Using ttag-cli for extraction

### ISSUE THREAD

**Issue by Jorgeewa** [ttag-org/ttag-cli#97]
Hi all, I am trying to use ttag-cli to extract my translation strings from tsx files. I have two issues:
1) It error out with the message: You can not use Identifier 'xxx' as an argument to gettext. This is because in my translation strategy, I translate some texts from the db so I pass a variable to gettext and I encode this msgid in my po file. This leads to my first question. How do I bypass this error message?
2) My second question relates to how I can resolve this issue in ttag should I decide to move my whole translation strategy to ttag. I read through the docs and I didn't find any potential solution to it.

**Comment by AlexMost** [comment]
Hi @Jorgeewa! Seems like I've got your point. You want to extract translations with ttag-cli, and have something like `gettext(someVariable)` ? There is an option for that in `babel-plugin-ttag` (which ttag-cli uses) but, still there is no such option in a ttag-cli. I can add that for you. Just wanted to clarify your usecase, can you provide some code snippet, that does not work?

**Comment by Jorgeewa** [comment]
Thanks for the response.
`    days.forEach((day, index) => {
        let newData = {
            label: gettext(day),
            method: 'animate',
            args: [[day], {
            mode: 'immediate',
            frame: {redraw: true, duration: 500},
            transition: {duration: 500}
        }]
    };` 
Here is a code snipped from plotly. So assuming day is a variable coming from the db and could be for example Monday, Tuesday, Wednesday etc.
I am using CRA so I don't think I have babel configurations. Ps I have managed to use another library to extract my translatable strings but my second question is whether I will have this problem if I wanted to switch to ttag or how is a problem like this resolved in ttag given that I didn't see and example of such in you docs.

**Comment by AlexMost** [comment]
Specifically for the CRA you can also use `macro` approach - https://github.com/ttag-org/ttag.macro. According to your code snipped, disable comment should work also.

**Comment by MrOrz** [comment]
> So assuming day is a variable coming from the db and could be for example Monday, Tuesday, Wednesday etc.

When I deal with string keys from database, I would manage a mapping table in my code base. For example, having something like:

```javascript
export const weekToTrasnlated = {
  monday: t`Monday`,
  tuesday: t`Tuesday`, 
  // ...
}
```
And have ttag-cli extract keys on the file above.

Then I can use:
```javascript
import {weekToTrasnlated} from '...';

days.forEach((day, index) => { let newData = { label: weekToTrasnlated[day], method: 'animate', args: [[day], { mode: 'immediate', frame: {redraw: true, duration: 500}, transition: {duration: 500} }] };
```

**Comment by Jorgeewa** [comment]
> > So assuming day is a variable coming from the db and could be for example Monday, Tuesday, Wednesday etc.
> 
> When I deal with string keys from database, I would manage a mapping table in my code base. For example, having something like:
> 
> ```js
> export const weekToTrasnlated = {
>   monday: t`Monday`,
>   tuesday: t`Tuesday`, 
>   // ...
> }
> ```
> 
> And have ttag-cli extract keys on the file above.
> 
> Then I can use:
> 
> ```js
> import {weekToTrasnlated} from '...';
> 
> days.forEach((day, index) => { let newData = { label: weekToTrasnlated[day], method: 'animate', args: [[day], { mode: 'immediate', frame: {redraw: true, duration: 500}, transition: {duration: 500} }] };
> ```

Nice example thanks. I will switch our current translation strategy to this as it is better than what we have now.
